import { Project } from './project';

export const PROJECTS: Project[] = [
    //{title:'Adsurge', description:'Main developer of Adsurge', image:"./assets/adsurge2.png",type_of_project:'Full Stack Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'https://www.adsurge.com/', code: 'none'},
    //{title:'Adcenter', description:'Developer of Adcenter', image:"./assets/adcenter.jpeg",type_of_project:'Full Stack Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'https://www.ad-center.com/', code: 'none'},
    {title:'My Portfolio', description:'I created from scratch my own Web Site', image:"./assets/my_portfolio.jpg",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'https://cesarcolina.com/', code: 'https://github.com/tratohecho3/My_Portfolio'},
    {title:'Mini-Spotify', description:'I created an app to find songs and play them using the spotify Api', image:"./assets/spotify.png",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'https://platzi-music-cqsleilvur.now.sh/', code: 'https://github.com/tratohecho3/platzi-music'},
    {title:'Mini-StackOverflow', description:'I created an app to ask and answer questions about technology', image:"./assets/stack-overflow.png",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'https://fast-crag-54971.herokuapp.com/', code: 'https://github.com/tratohecho3/platzi-overflow'},
    {title:'My Social network', description:'I created from scratch my own Social Network.', image:"./assets/social_network.png",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'none', code: 'https://github.com/tratohecho3/social_network'},
    {title:'Business Localizator', description:'It is an app to create a mock business and find it in the google maps API', image:"./assets/maps.jpg",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'https://platzisquare-410ad.firebaseapp.com/', code: 'https://github.com/tratohecho3/PlatziSquare'},
    {title:'University exercises', description:'A big set of projects and exercises of Algorithms and others', image:"./assets/github.png",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'none', code: 'https://github.com/tratohecho3'},
    {title:'Games', description:'I created a simple space invaders and a reduced chess game', image:"./assets/chess.png",type_of_project:'Frontend Development',techologies:['html','css','javascript','angular','bootstrap'], view: 'none', code: 'https://github.com/tratohecho3'},


]